/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mixregui;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author adityaponnada
 */
public class stageTwoRegs extends javax.swing.JFrame {
    
    //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
   stageOneRegs stageOne;
   NewModel newModel2;
   mixregGUI mixregGUIStageTwo;
    
   static DefaultListModel<String> stageTwoListModel;
   static DefaultListModel<String> stageTwoLevelTwo;
   
   static boolean isStageTwoSubmitClicked = false;

    /**
     * Creates new form stageTwoRegs
     */
    public stageTwoRegs() {
        initComponents();
        //create list models
        
        newModel2 = new NewModel();
        
        if (!isStageTwoSubmitClicked){
            stageTwoListModel = new DefaultListModel<String>();
            stageTwoLevelTwo = new DefaultListModel<String>();
        
        } else {
        StageTwoAllVariables.setModel(stageTwoListModel);
        StageTwoLevelTwoVariables.setModel(stageTwoLevelTwo);
        
        }
       
       stageTwoSubmitButton.setEnabled(false);
       
      
       setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stageTwoAddButton = new javax.swing.JButton();
        stageTwoRemoveButton = new javax.swing.JButton();
        stageTwoResetButton = new javax.swing.JButton();
        stageTwoSubmitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StageTwoAllVariables = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        StageTwoLevelTwoVariables = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Variables");

        jLabel2.setText("Level-II (Time Invariant)");

        stageTwoAddButton.setText("Add");
        stageTwoAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoAddButtonActionPerformed(evt);
            }
        });

        stageTwoRemoveButton.setText("Remove");
        stageTwoRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoRemoveButtonActionPerformed(evt);
            }
        });

        stageTwoResetButton.setText("Reset");
        stageTwoResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoResetButtonActionPerformed(evt);
            }
        });

        stageTwoSubmitButton.setText("Submit");
        stageTwoSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoSubmitButtonActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(StageTwoAllVariables);

        jScrollPane2.setViewportView(StageTwoLevelTwoVariables);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stageTwoResetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stageTwoAddButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stageTwoRemoveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(422, Short.MAX_VALUE)
                    .addComponent(stageTwoSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(stageTwoAddButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stageTwoRemoveButton))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stageTwoResetButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 101, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(494, Short.MAX_VALUE)
                    .addComponent(stageTwoSubmitButton)
                    .addGap(5, 5, 5)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stageTwoSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoSubmitButtonActionPerformed
        //dispose closes the window
        //mixregGUI.
        isStageTwoSubmitClicked = true;
        
        mixregGUIStageTwo = newModel2.getMixReg();
        mixregGUIStageTwo.updateStageTwoGrid_version2(stageTwoLevelTwo);
        this.dispose();
    }//GEN-LAST:event_stageTwoSubmitButtonActionPerformed

    private void stageTwoAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoAddButtonActionPerformed
        
        //Add items to the model and then copy it to the UI list
        stageTwoLevelTwo.addElement(StageTwoAllVariables.getSelectedValue());
        StageTwoLevelTwoVariables.setModel(stageTwoLevelTwo);
        
        
        
        stageTwoSubmitButton.setEnabled(true);
        
    }//GEN-LAST:event_stageTwoAddButtonActionPerformed

    private void stageTwoRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoRemoveButtonActionPerformed
        
        //Remove an item from the model
        stageTwoSubmitButton.setEnabled(true);
        stageTwoLevelTwo.remove(StageTwoLevelTwoVariables.getSelectedIndex());
    }//GEN-LAST:event_stageTwoRemoveButtonActionPerformed

    private void stageTwoResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoResetButtonActionPerformed
        stageTwoLevelTwo.clear();
    }//GEN-LAST:event_stageTwoResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stageTwoRegs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> StageTwoAllVariables;
    private javax.swing.JList<String> StageTwoLevelTwoVariables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton stageTwoAddButton;
    private javax.swing.JButton stageTwoRemoveButton;
    private javax.swing.JButton stageTwoResetButton;
    private javax.swing.JButton stageTwoSubmitButton;
    // End of variables declaration//GEN-END:variables


    
  public void updateStageTwoVariables(DefaultListModel<String> defaultListModel){
      
     //updates variables in stage two list (to add regressors)
    //Add model to stage two variables, to display items    
    StageTwoAllVariables.setModel(defaultListModel);
    
    StageTwoAllVariables.setSelectedIndex(2);
}

}
