/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mixregui;

import java.awt.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;

/**
 *
 * @author adityaponnada
 */
public class stageOneRegs extends javax.swing.JFrame {
    
   // declare required jFrame
    
    NewModel newModel2;
    
    mixregGUI mixregStageOne;
    
    stageTwoRegs stageTwo;
    
    static String[] variableNamesList;
    
    static DefaultListModel<String> varList;
    
    static DefaultListModel<String> levelOneList;
    
    static DefaultListModel<String> levelTwoList;
    
    static boolean isSubmitClicked = false;
    
    /**
     * Creates new form stageOneRegs
     */
    public stageOneRegs() {
       initComponents();
       
       newModel2 = new NewModel();
       setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
       //get variable names from the data set
       variableNamesList = newModel2.getVariableNames();
       
       if (!isSubmitClicked){
       varList = new DefaultListModel<String>();
       levelOneList = new DefaultListModel<String>();
       levelTwoList = new DefaultListModel<String>();
       
       } else{
           AllVariablesList.removeAll();
        AllVariablesList.setModel(varList);
        AllVariablesList.setSelectedIndex(0);
        StageOneLevelOneList.removeAll();
        StageOneLevelOneList.setModel(levelOneList);
        StageOneLevelTwoList.removeAll();
        StageOneLevelTwoList.setModel(levelTwoList);
       }
       
       
       stageOneSubmitButton.setEnabled(false);
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        stageOneSubmitButton = new javax.swing.JButton();
        stageOneResetButton = new javax.swing.JButton();
        removeLevelButton = new javax.swing.JButton();
        levelOneAddButton = new javax.swing.JButton();
        removeLevelTwoButton = new javax.swing.JButton();
        addLevelTwoButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AllVariablesList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        StageOneLevelOneList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        StageOneLevelTwoList = new javax.swing.JList<>();

        label1.setText("label1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Stage 1 Regressors");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Variables");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));

        jLabel2.setText("Level-I (Time Variant)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, -1, -1));

        jLabel3.setText("Level-II (Time Invariant)");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));

        stageOneSubmitButton.setText("Submit");
        stageOneSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageOneSubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stageOneSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 480, -1, -1));

        stageOneResetButton.setText("Reset");
        stageOneResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageOneResetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stageOneResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 89, -1));

        removeLevelButton.setText("Remove");
        removeLevelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLevelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeLevelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 125, -1, -1));

        levelOneAddButton.setText("Add");
        levelOneAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                levelOneAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(levelOneAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 90, 93, -1));

        removeLevelTwoButton.setText("Remove");
        removeLevelTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeLevelTwoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(removeLevelTwoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 345, -1, -1));

        addLevelTwoButton.setText("Add");
        addLevelTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLevelTwoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(addLevelTwoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 310, 93, -1));

        jScrollPane1.setViewportView(AllVariablesList);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(32, 72, 198, 388));

        jScrollPane2.setViewportView(StageOneLevelOneList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 72, 287, 164));

        jScrollPane3.setViewportView(StageOneLevelTwoList);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 297, 287, 163));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stageOneSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageOneSubmitButtonActionPerformed
       
        stageTwo = new stageTwoRegs();
        isSubmitClicked = true;
        
        
        //get the instance of the mixReg model declared
        mixregStageOne = newModel2.getMixReg();
        
        //update regressors on stage one regressors window
       // mixregStageOne.updateRegressors(getSelectedLevelOneVars(), getSelectedLevelTwoVars());
       //mixregStageOne.updateLevelOneRegGrid(levelOneList);
       mixregStageOne.updateLevelTwoGrid_version2(levelTwoList);
       mixregStageOne.updateLevelOneGrid_version2(levelOneList);
        
        this.dispose();
    }//GEN-LAST:event_stageOneSubmitButtonActionPerformed

    private void levelOneAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_levelOneAddButtonActionPerformed
        
        levelOneList.addElement(AllVariablesList.getSelectedValue());
        StageOneLevelOneList.setModel(levelOneList);
        //remove the variable once it is added to levelOne regressors
        varList.remove(AllVariablesList.getSelectedIndex());
        
        stageOneSubmitButton.setEnabled(true);
       
    }//GEN-LAST:event_levelOneAddButtonActionPerformed

    private void addLevelTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLevelTwoButtonActionPerformed
        
        stageOneSubmitButton.setEnabled(true);
        
        levelTwoList.addElement(AllVariablesList.getSelectedValue());
        StageOneLevelTwoList.setModel(levelTwoList);
        
        varList.remove(AllVariablesList.getSelectedIndex());
        
    }//GEN-LAST:event_addLevelTwoButtonActionPerformed

    private void removeLevelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLevelButtonActionPerformed
        
        stageOneSubmitButton.setEnabled(true);
        
        varList.addElement(StageOneLevelOneList.getSelectedValue());
        
        AllVariablesList.setModel(varList);
        
        levelOneList.remove(StageOneLevelOneList.getSelectedIndex());
        
    }//GEN-LAST:event_removeLevelButtonActionPerformed

    private void removeLevelTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeLevelTwoButtonActionPerformed
        
        stageOneSubmitButton.setEnabled(true);
        
        varList.addElement(StageOneLevelTwoList.getSelectedValue());
        
        AllVariablesList.setModel(varList);
        
        levelTwoList.remove(StageOneLevelTwoList.getSelectedIndex());
    }//GEN-LAST:event_removeLevelTwoButtonActionPerformed

    private void stageOneResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageOneResetButtonActionPerformed
       
        //clear lists on reset
        
        updateAllVariables();
        
        levelOneList.clear();
        levelTwoList.clear();
    }//GEN-LAST:event_stageOneResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stageOneRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stageOneRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stageOneRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stageOneRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stageOneRegs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> AllVariablesList;
    private javax.swing.JList<String> StageOneLevelOneList;
    private javax.swing.JList<String> StageOneLevelTwoList;
    private javax.swing.JButton addLevelTwoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private java.awt.Label label1;
    private javax.swing.JButton levelOneAddButton;
    private javax.swing.JButton removeLevelButton;
    private javax.swing.JButton removeLevelTwoButton;
    private javax.swing.JButton stageOneResetButton;
    private javax.swing.JButton stageOneSubmitButton;
    // End of variables declaration//GEN-END:variables

public void updateAllVariables(){
    
    for (int j=0; j<variableNamesList.length; j++){
        varList.addElement(variableNamesList[j]);
    }
   
    AllVariablesList.setModel(varList);
    AllVariablesList.setSelectedIndex(0);
}

public DefaultListModel<String> getListModel(){

    System.out.println("inside getListModel()");
    
    return varList;
}


public DefaultComboBoxModel<String> getSelectedLevelOneVars(){

DefaultComboBoxModel<String> levelOneCombo = new DefaultComboBoxModel();

for (int j = 0; j< levelOneList.getSize(); j++){
    
    levelOneCombo.addElement(levelOneList.getElementAt(j));

}

return levelOneCombo;

}

public DefaultComboBoxModel<String> getSelectedLevelTwoVars(){

DefaultComboBoxModel<String> levelTwoCombo = new DefaultComboBoxModel();
    
    for (int j = 0; j< levelTwoList.getSize(); j++){
    
    levelTwoCombo.addElement(levelTwoList.getElementAt(j));

}
return levelTwoCombo;

}

/*
public boolean isDisaggVarianceChecked(){
    
    boolean checked = false;
    
    if (disaggVarianceCheckBox.isSelected() == true){
        checked = true;
    
    } else {
        checked = false;
    
    }
    return checked;
}*/
}
