/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mixregui;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

/**
 *
 * @author adityaponnada
 */
public class stageTwoRegs extends javax.swing.JFrame {
    
    //setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    
   stageOneRegs stageOne;
   NewModel newModel2;
   mixregGUI mixregGUIStageTwo;
    
   static DefaultListModel<String> stageTwoListModel;
   static DefaultListModel<String> stageTwoLevelTwo;
   
   static boolean isStageTwoSubmitClicked = false;

    /**
     * Creates new form stageTwoRegs
     */
    public stageTwoRegs() {
        initComponents();
        //create list models
        
        newModel2 = new NewModel();
        
        if (!isStageTwoSubmitClicked){
            stageTwoListModel = new DefaultListModel<String>();
            stageTwoLevelTwo = new DefaultListModel<String>();
        
        } else {
        StageTwoAllVariables.setModel(stageTwoListModel);
        StageTwoLevelTwoVariables.setModel(stageTwoLevelTwo);
        
        }
       
       stageTwoSubmitButton.setEnabled(false);
       
      
       setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        stageTwoAddButton = new javax.swing.JButton();
        stageTwoRemoveButton = new javax.swing.JButton();
        stageTwoResetButton = new javax.swing.JButton();
        stageTwoSubmitButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        StageTwoAllVariables = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        StageTwoLevelTwoVariables = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Stage 2 regressors");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Variables");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setText("Level-II (Time Invariant)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, -1, -1));

        stageTwoAddButton.setText("Add");
        stageTwoAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoAddButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stageTwoAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 85, 89, -1));

        stageTwoRemoveButton.setText("Remove");
        stageTwoRemoveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoRemoveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stageTwoRemoveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 120, 89, -1));

        stageTwoResetButton.setText("Reset");
        stageTwoResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoResetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stageTwoResetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 460, 96, -1));

        stageTwoSubmitButton.setText("Submit");
        stageTwoSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stageTwoSubmitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(stageTwoSubmitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 460, 96, -1));

        jScrollPane1.setViewportView(StageTwoAllVariables);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 55, 179, 372));

        jScrollPane2.setViewportView(StageTwoLevelTwoVariables);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 55, 162, 177));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stageTwoSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoSubmitButtonActionPerformed
        //dispose closes the window
        //mixregGUI.
        isStageTwoSubmitClicked = true;
        
        mixregGUIStageTwo = newModel2.getMixReg();
        mixregGUIStageTwo.updateStageTwoGrid_version2(stageTwoLevelTwo);
        this.dispose();
    }//GEN-LAST:event_stageTwoSubmitButtonActionPerformed

    private void stageTwoAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoAddButtonActionPerformed
        
        //Add items to the model and then copy it to the UI list
        stageTwoLevelTwo.addElement(StageTwoAllVariables.getSelectedValue());
        StageTwoLevelTwoVariables.setModel(stageTwoLevelTwo);
        
        
        
        stageTwoSubmitButton.setEnabled(true);
        
    }//GEN-LAST:event_stageTwoAddButtonActionPerformed

    private void stageTwoRemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoRemoveButtonActionPerformed
        
        //Remove an item from the model
        stageTwoSubmitButton.setEnabled(true);
        stageTwoLevelTwo.remove(StageTwoLevelTwoVariables.getSelectedIndex());
    }//GEN-LAST:event_stageTwoRemoveButtonActionPerformed

    private void stageTwoResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stageTwoResetButtonActionPerformed
        stageTwoLevelTwo.clear();
    }//GEN-LAST:event_stageTwoResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(stageTwoRegs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new stageTwoRegs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> StageTwoAllVariables;
    private javax.swing.JList<String> StageTwoLevelTwoVariables;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton stageTwoAddButton;
    private javax.swing.JButton stageTwoRemoveButton;
    private javax.swing.JButton stageTwoResetButton;
    private javax.swing.JButton stageTwoSubmitButton;
    // End of variables declaration//GEN-END:variables


    
  public void updateStageTwoVariables(DefaultListModel<String> defaultListModel){
      
     //updates variables in stage two list (to add regressors)
    //Add model to stage two variables, to display items    
    StageTwoAllVariables.setModel(defaultListModel);
    
    StageTwoAllVariables.setSelectedIndex(2);
}

}
